/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.healthconnect.form;

import com.healthconnect.event.EventProfileBar;
import com.healthconnect.event.PublicEvent;
import com.healthconnect.model.Model_User_Account;
import com.healthconnect.service.Service;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author xyh10
 */
public class Menu_Profile extends javax.swing.JPanel {

    /**
     * Creates new form Menu_Left
     */
    
    public Menu_Profile() {
        initComponents();
        
        PublicEvent.getInstance().addEventProfileBar(new EventProfileBar(){
            @Override
            public void showRrofile() {
                showProfileImage();
            }
            
        });
        
        
    }

    public void showProfileImage() {
        Icon icon;
        try {
            icon= new ImageIcon("client_data/" + Service.getInstance().getUser().getImage());
            System.out.println("1");
        } catch (Exception e) {
            icon= new ImageIcon(getClass().getResource("/com/healthconnect/icon/image_not_found.png"));      
            System.out.println("2");
        }
        
        
        profile.setImage(icon);
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profile = new com.healthconnect.swing.ImageAvatar();
        logoutBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));

        profile.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/healthconnect/icon/zzs.jpg"))); // NOI18N

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/healthconnect/icon/log-out.png"))); // NOI18N
        logoutBtn.setBorder(null);
        logoutBtn.setContentAreaFilled(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(438, 438, 438)
                .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        PublicEvent.getInstance().getEventLogin().logout();
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logoutBtn;
    private com.healthconnect.swing.ImageAvatar profile;
    // End of variables declaration//GEN-END:variables
}
